export enum ChartCommons {
  TRANSITION_DURATION = 500,
  BAR_BAND = 40,
  BAR_GAP = 5,
  COMPONENT_MARGIN = 15,
  CHART_HEADER_HEIGHT = 40,
  COLOR_PREVIEW_SIZE = 10,
  COLOR_PREVIEW_MARGIN = 5,
  LABEL_HEIGHT = 18
}
